extends: airbnb
rules:
  no-undef: off
  comma-dangle: off
  no-console: off
  max-len: off
  no-param-reassign: off
  object-curly-newline: off
  no-underscore-dangle: off
  function-paren-newline: off
  no-use-before-define: off
  react/forbid-prop-types: off
  import/no-named-as-default: off
  jsx-a11y/anchor-is-valid: off
  import/no-dynamic-require: off

