extends: airbnb
rules:
  no-undef: off
  comma-dangle: off
  no-console: off
  no-param-reassign: off
  function-paren-newline: off
  no-use-before-define: off
  react/prefer-stateless-function: off
  react/jsx-filename-extension: off
